#!/usr/bin/env bash
set -euo pipefail
cd /home/akshay/Projects/queue-system
M=supabase/migrations
OUT=supabase/setup-fresh-db.sql

# Guard the three non-idempotent `alter publication` lines in schema.sql.
guard_publication() {
  sed -E 's|^alter publication supabase_realtime add table (public\.[a-z_]+);|DO $$ BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE \1; EXCEPTION WHEN duplicate_object THEN NULL; END $$;|'
}

section() { printf '\n\n-- ══════════════════════════════════════════════════════════════\n-- %s\n-- ══════════════════════════════════════════════════════════════\n\n' "$1"; }

{
cat <<'HDR'
-- ══════════════════════════════════════════════════════════════
-- FRESH DATABASE SETUP — full stack, both products
-- ══════════════════════════════════════════════════════════════
-- Generated by supabase/build-bundle.sh — DO NOT EDIT BY HAND.
-- Edit supabase/schema.sql or a file in supabase/migrations/ and re-run
-- the generator instead.
--
-- Contents, in dependency order:
--   1. supabase/schema.sql               — base queue product (clean slate)
--   2. supabase/migrations/*.sql         — every legacy migration, in order
--   3. 20260825_school_queue_system.sql  — the school queue product
--   4. 20260826_license_key_vertical.sql — which product a key entitles
--
-- ⚠ DESTRUCTIVE. schema.sql opens with `drop table … cascade`, and this file
--   additionally drops `counters` and the school_* tables so a re-run is a
--   true clean slate rather than leaving orphaned tables behind. Intended for
--   a brand-new project. Do not run against a database holding real data.
--
-- Run it whole: Supabase Dashboard → SQL Editor → paste → Run.
-- ══════════════════════════════════════════════════════════════

create extension if not exists "pgcrypto";

-- ── Clean slate for tables schema.sql does not itself drop ────
-- schema.sql's `drop table public.customers cascade` removes the FK
-- constraints pointing at it but leaves these tables standing, so drop them
-- here (children first) to keep a re-run honest.
drop table if exists public.school_activity_logs       cascade;
drop table if exists public.school_tokens              cascade;
drop table if exists public.school_counter_departments cascade;
drop table if exists public.school_counters            cascade;
drop table if exists public.school_department_days     cascade;
drop table if exists public.school_departments         cascade;
drop table if exists public.school_settings            cascade;
drop table if exists public.counters                   cascade;
HDR

section "1. BASE SCHEMA  (supabase/schema.sql)"
guard_publication < supabase/schema.sql

section "2. MIGRATION  001_license_key_customer_link.sql"
cat $M/001_license_key_customer_link.sql

section "2. MIGRATION  002_screen_announcement_lang.sql"
cat $M/002_screen_announcement_lang.sql

section "3. MIGRATION  20260630_create_counters_table.sql"
# The policy created here is unnamed-role and replaced by 20260703; add a
# DROP so this bundle survives a re-run.
sed 's|^create policy "service role full access"|drop policy if exists "service role full access" on counters;\ncreate policy "service role full access"|' \
  $M/20260630_create_counters_table.sql

section "4. MIGRATION  20260630_add_kitchen_status.sql"
cat $M/20260630_add_kitchen_status.sql

section "5. MIGRATION  20260703_counter_presence.sql"
cat $M/20260703_counter_presence.sql

section "6. MIGRATION  20260703_add_order_counter.sql"
cat $M/20260703_add_order_counter.sql

section "7. MIGRATION  20260704_counter_presence_toggle.sql"
cat $M/20260704_counter_presence_toggle.sql

section "8. MIGRATION  20260704_user_branches_single.sql"
head -4 $M/20260704_user_branches_single.sql
cat <<'UB'
-- (ADD CONSTRAINT has no IF NOT EXISTS; guarded so the bundle is re-runnable.)
DO $$ BEGIN
  ALTER TABLE user_branches ADD CONSTRAINT user_branches_one_per_user UNIQUE (user_id);
EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
UB

section "9. MIGRATION  20260705_counter_accepting_orders.sql"
cat $M/20260705_counter_accepting_orders.sql

section "10. MIGRATION  20260705_kitchen_bypassed_activity_type.sql"
cat $M/20260705_kitchen_bypassed_activity_type.sql

section "11. MIGRATION  20260705_common_bucket_public.sql"
cat <<'BKT'
-- The original migration only flips the flag and assumes the bucket was made
-- by hand in the dashboard. On a fresh project it does not exist yet, so
-- create it here — otherwise every ad upload 404s and the migration is a
-- silent no-op affecting 0 rows.
insert into storage.buckets (id, name, public)
values ('common-bucket', 'common-bucket', true)
on conflict (id) do update set public = true;
BKT
cat $M/20260705_common_bucket_public.sql

section "12. MIGRATION  20260709_add_call_counter.sql"
cat $M/20260709_add_call_counter.sql

section "13. SCHOOL QUEUE  20260825_school_queue_system.sql"
cat $M/20260825_school_queue_system.sql

section "14. MIGRATION  20260826_license_key_vertical.sql"
cat $M/20260826_license_key_vertical.sql

printf '\n\n-- ── END OF BUNDLE ─────────────────────────────────────────────\n'
} > "$OUT"

echo "wrote $OUT ($(wc -l < "$OUT") lines)"
