import type { QueueEntry, ActivityLog } from "./types"

const now = new Date()
const mins = (m: number) => new Date(now.getTime() - m * 60 * 1000).toISOString()

export const initialQueue: QueueEntry[] = [
  {
    id: "entry-12",
    queueNumber: 12,
    name: "Ana Torres",
    phone: "+1 555-012-3456",
    email: "ana.torres@email.com",
    service: "Consultation",
    type: "normal",
    status: "completed",
    joinedAt: mins(180),
    startedAt: mins(165),
    completedAt: mins(150),
    trackingToken: "Q-12",
  },
  {
    id: "entry-13",
    queueNumber: 13,
    name: "Bob Chen",
    phone: "+1 555-013-4567",
    email: "bob.chen@email.com",
    service: "Food Order",
    type: "vip",
    status: "completed",
    joinedAt: mins(165),
    startedAt: mins(148),
    completedAt: mins(133),
    trackingToken: "Q-13",
  },
  {
    id: "entry-14",
    queueNumber: 14,
    name: "Carol Davis",
    phone: "+1 555-014-5678",
    email: "carol.davis@email.com",
    service: "Document Verification",
    type: "normal",
    status: "completed",
    joinedAt: mins(150),
    startedAt: mins(132),
    completedAt: mins(117),
    trackingToken: "Q-14",
  },
  {
    id: "entry-15",
    queueNumber: 15,
    name: "Diana Smith",
    phone: "+1 555-015-6789",
    email: "diana.smith@email.com",
    service: "Repair Service",
    type: "priority",
    status: "completed",
    joinedAt: mins(135),
    startedAt: mins(116),
    completedAt: mins(99),
    trackingToken: "Q-15",
  },
  {
    id: "entry-16",
    queueNumber: 16,
    name: "Eric Johnson",
    phone: "+1 555-016-7890",
    email: "eric.johnson@email.com",
    service: "Consultation",
    type: "normal",
    status: "completed",
    joinedAt: mins(110),
    startedAt: mins(98),
    completedAt: mins(82),
    trackingToken: "Q-16",
  },
  {
    id: "entry-17",
    queueNumber: 17,
    name: "Fiona Williams",
    phone: "+1 555-017-8901",
    email: "fiona.w@email.com",
    service: "Food Order",
    type: "vip",
    status: "completed",
    joinedAt: mins(90),
    startedAt: mins(81),
    completedAt: mins(65),
    trackingToken: "Q-17",
  },
  {
    id: "entry-18",
    queueNumber: 18,
    name: "George Brown",
    phone: "+1 555-018-9012",
    email: "george.brown@email.com",
    service: "Document Verification",
    type: "priority",
    status: "in-progress",
    joinedAt: mins(70),
    startedAt: mins(5),
    trackingToken: "Q-18",
  },
  {
    id: "entry-19",
    queueNumber: 19,
    name: "Hannah Lee",
    phone: "+1 555-019-0123",
    email: "hannah.lee@email.com",
    service: "Repair Service",
    type: "normal",
    status: "waiting",
    joinedAt: mins(60),
    trackingToken: "Q-19",
  },
  {
    id: "entry-20",
    queueNumber: 20,
    name: "Ivan Martinez",
    phone: "+1 555-020-1234",
    email: "ivan.m@email.com",
    service: "Consultation",
    type: "vip",
    status: "waiting",
    joinedAt: mins(55),
    trackingToken: "Q-20",
  },
  {
    id: "entry-21",
    queueNumber: 21,
    name: "Julia Kim",
    phone: "+1 555-021-2345",
    email: "julia.kim@email.com",
    service: "Food Order",
    type: "normal",
    status: "waiting",
    joinedAt: mins(48),
    trackingToken: "Q-21",
  },
  {
    id: "entry-22",
    queueNumber: 22,
    name: "Kevin Park",
    phone: "+1 555-022-3456",
    email: "kevin.park@email.com",
    service: "Document Verification",
    type: "priority",
    status: "waiting",
    joinedAt: mins(42),
    trackingToken: "Q-22",
  },
  {
    id: "entry-23",
    queueNumber: 23,
    name: "Luna Garcia",
    phone: "+1 555-023-4567",
    email: "luna.garcia@email.com",
    service: "Repair Service",
    type: "normal",
    status: "waiting",
    joinedAt: mins(36),
    trackingToken: "Q-23",
  },
  {
    id: "entry-24",
    queueNumber: 24,
    name: "Mike Patel",
    phone: "+1 555-024-5678",
    email: "mike.patel@email.com",
    service: "Consultation",
    type: "vip",
    status: "waiting",
    joinedAt: mins(30),
    trackingToken: "Q-24",
  },
  {
    id: "entry-25",
    queueNumber: 25,
    name: "Nina Roberts",
    phone: "+1 555-025-6789",
    email: "nina.r@email.com",
    service: "Food Order",
    type: "normal",
    status: "waiting",
    joinedAt: mins(25),
    trackingToken: "Q-25",
  },
  {
    id: "entry-26",
    queueNumber: 26,
    name: "Oscar Thompson",
    phone: "+1 555-026-7890",
    email: "oscar.t@email.com",
    service: "Document Verification",
    type: "normal",
    status: "waiting",
    joinedAt: mins(20),
    trackingToken: "Q-26",
  },
  {
    id: "entry-27",
    queueNumber: 27,
    name: "Priya Sharma",
    phone: "+1 555-027-8901",
    email: "priya.s@email.com",
    service: "Repair Service",
    type: "priority",
    status: "waiting",
    joinedAt: mins(15),
    trackingToken: "Q-27",
  },
  {
    id: "entry-28",
    queueNumber: 28,
    name: "Quincy Adams",
    phone: "+1 555-028-9012",
    email: "quincy.a@email.com",
    service: "Consultation",
    type: "normal",
    status: "waiting",
    joinedAt: mins(8),
    trackingToken: "Q-28",
  },
]

export const initialActivityLogs: ActivityLog[] = [
  {
    id: "log-1",
    timestamp: mins(65),
    message: "Queue #17 completed",
    type: "completed",
    queueNumber: 17,
  },
  {
    id: "log-2",
    timestamp: mins(5),
    message: "Queue #18 started",
    type: "called",
    queueNumber: 18,
  },
  {
    id: "log-3",
    timestamp: mins(8),
    message: "Queue #28 joined",
    type: "joined",
    queueNumber: 28,
  },
  {
    id: "log-4",
    timestamp: mins(15),
    message: "Queue #27 joined",
    type: "joined",
    queueNumber: 27,
  },
  {
    id: "log-5",
    timestamp: mins(20),
    message: "Queue #26 joined",
    type: "joined",
    queueNumber: 26,
  },
  {
    id: "log-6",
    timestamp: mins(25),
    message: "Queue #25 joined",
    type: "joined",
    queueNumber: 25,
  },
]

export const hourlyVolumeData = [
  { hour: "08:00", customers: 2 },
  { hour: "09:00", customers: 5 },
  { hour: "10:00", customers: 12 },
  { hour: "11:00", customers: 18 },
  { hour: "12:00", customers: 22 },
  { hour: "13:00", customers: 19 },
  { hour: "14:00", customers: 15 },
  { hour: "15:00", customers: 20 },
  { hour: "16:00", customers: 14 },
  { hour: "17:00", customers: 8 },
  { hour: "18:00", customers: 4 },
]

export const weeklyTrendData = [
  { day: "Mon", completed: 38, joined: 42 },
  { day: "Tue", completed: 45, joined: 48 },
  { day: "Wed", completed: 52, joined: 55 },
  { day: "Thu", completed: 61, joined: 65 },
  { day: "Fri", completed: 73, joined: 78 },
  { day: "Sat", completed: 89, joined: 94 },
  { day: "Sun", completed: 64, joined: 68 },
]

export const statusBreakdownData = [
  { name: "Completed", value: 6, fill: "#10b981" },
  { name: "In Progress", value: 1, fill: "#8b5cf6" },
  { name: "Waiting", value: 10, fill: "#3b82f6" },
]
