import type { QueueEntryDTO as QueueEntry, ActivityLogDTO as ActivityLog } from './db/types'

const now = new Date()
const mins = (m: number) => new Date(now.getTime() - m * 60 * 1000).toISOString()

const DEMO_BRANCH_ID = 'demo-branch-id'
const DEMO_CUSTOMER_ID = 'demo-customer-id'

export const initialQueue: QueueEntry[] = [
  { id: 'entry-12', customerId: DEMO_CUSTOMER_ID, branchId: DEMO_BRANCH_ID, queueNumber: 12, billNumber: 'B-1001', customerName: '', phone: '', status: 'completed', source: 'admin', kitchenStatus: 'pending' as const, joinedAt: mins(180), startedAt: mins(165), completedAt: mins(150), callCount: 1, recallCount: 0, notes: '', createdAt: mins(180) },
  { id: 'entry-13', customerId: DEMO_CUSTOMER_ID, branchId: DEMO_BRANCH_ID, queueNumber: 13, billNumber: 'B-1002', customerName: '', phone: '', status: 'completed', source: 'admin', kitchenStatus: 'pending' as const, joinedAt: mins(165), startedAt: mins(148), completedAt: mins(133), callCount: 1, recallCount: 0, notes: '', createdAt: mins(165) },
  { id: 'entry-14', customerId: DEMO_CUSTOMER_ID, branchId: DEMO_BRANCH_ID, queueNumber: 14, billNumber: 'B-1003', customerName: '', phone: '', status: 'completed', source: 'admin', kitchenStatus: 'pending' as const, joinedAt: mins(150), startedAt: mins(132), completedAt: mins(117), callCount: 1, recallCount: 0, notes: '', createdAt: mins(150) },
  { id: 'entry-15', customerId: DEMO_CUSTOMER_ID, branchId: DEMO_BRANCH_ID, queueNumber: 15, billNumber: 'B-1004', customerName: '', phone: '', status: 'completed', source: 'admin', kitchenStatus: 'pending' as const, joinedAt: mins(135), startedAt: mins(116), completedAt: mins(99), callCount: 1, recallCount: 0, notes: '', createdAt: mins(135) },
  { id: 'entry-16', customerId: DEMO_CUSTOMER_ID, branchId: DEMO_BRANCH_ID, queueNumber: 16, billNumber: 'B-1005', customerName: '', phone: '', status: 'completed', source: 'admin', kitchenStatus: 'pending' as const, joinedAt: mins(110), startedAt: mins(98), completedAt: mins(82), callCount: 1, recallCount: 0, notes: '', createdAt: mins(110) },
  { id: 'entry-17', customerId: DEMO_CUSTOMER_ID, branchId: DEMO_BRANCH_ID, queueNumber: 17, billNumber: 'B-1006', customerName: '', phone: '', status: 'completed', source: 'admin', kitchenStatus: 'pending' as const, joinedAt: mins(90), startedAt: mins(81), completedAt: mins(65), callCount: 1, recallCount: 0, notes: '', createdAt: mins(90) },
  { id: 'entry-18', customerId: DEMO_CUSTOMER_ID, branchId: DEMO_BRANCH_ID, queueNumber: 18, billNumber: 'B-1007', customerName: '', phone: '', status: 'in-progress', source: 'admin', kitchenStatus: 'pending' as const, joinedAt: mins(70), startedAt: mins(5), completedAt: undefined, callCount: 1, recallCount: 0, notes: '', createdAt: mins(70) },
  { id: 'entry-19', customerId: DEMO_CUSTOMER_ID, branchId: DEMO_BRANCH_ID, queueNumber: 19, billNumber: 'B-1008', customerName: '', phone: '', status: 'waiting', source: 'admin', kitchenStatus: 'pending' as const, joinedAt: mins(60), startedAt: undefined, completedAt: undefined, callCount: 0, recallCount: 0, notes: '', createdAt: mins(60) },
  { id: 'entry-20', customerId: DEMO_CUSTOMER_ID, branchId: DEMO_BRANCH_ID, queueNumber: 20, billNumber: 'B-1009', customerName: '', phone: '', status: 'waiting', source: 'admin', kitchenStatus: 'pending' as const, joinedAt: mins(55), startedAt: undefined, completedAt: undefined, callCount: 0, recallCount: 0, notes: '', createdAt: mins(55) },
  { id: 'entry-21', customerId: DEMO_CUSTOMER_ID, branchId: DEMO_BRANCH_ID, queueNumber: 21, billNumber: 'B-1010', customerName: '', phone: '', status: 'waiting', source: 'admin', kitchenStatus: 'pending' as const, joinedAt: mins(48), startedAt: undefined, completedAt: undefined, callCount: 0, recallCount: 0, notes: '', createdAt: mins(48) },
  { id: 'entry-22', customerId: DEMO_CUSTOMER_ID, branchId: DEMO_BRANCH_ID, queueNumber: 22, billNumber: 'B-1011', customerName: '', phone: '', status: 'waiting', source: 'admin', kitchenStatus: 'pending' as const, joinedAt: mins(42), startedAt: undefined, completedAt: undefined, callCount: 0, recallCount: 0, notes: '', createdAt: mins(42) },
  { id: 'entry-23', customerId: DEMO_CUSTOMER_ID, branchId: DEMO_BRANCH_ID, queueNumber: 23, billNumber: 'B-1012', customerName: '', phone: '', status: 'waiting', source: 'admin', kitchenStatus: 'pending' as const, joinedAt: mins(36), startedAt: undefined, completedAt: undefined, callCount: 0, recallCount: 0, notes: '', createdAt: mins(36) },
  { id: 'entry-24', customerId: DEMO_CUSTOMER_ID, branchId: DEMO_BRANCH_ID, queueNumber: 24, billNumber: 'B-1013', customerName: '', phone: '', status: 'waiting', source: 'admin', kitchenStatus: 'pending' as const, joinedAt: mins(30), startedAt: undefined, completedAt: undefined, callCount: 0, recallCount: 0, notes: '', createdAt: mins(30) },
  { id: 'entry-25', customerId: DEMO_CUSTOMER_ID, branchId: DEMO_BRANCH_ID, queueNumber: 25, billNumber: 'B-1014', customerName: '', phone: '', status: 'waiting', source: 'admin', kitchenStatus: 'pending' as const, joinedAt: mins(25), startedAt: undefined, completedAt: undefined, callCount: 0, recallCount: 0, notes: '', createdAt: mins(25) },
  { id: 'entry-26', customerId: DEMO_CUSTOMER_ID, branchId: DEMO_BRANCH_ID, queueNumber: 26, billNumber: 'B-1015', customerName: '', phone: '', status: 'waiting', source: 'admin', kitchenStatus: 'pending' as const, joinedAt: mins(20), startedAt: undefined, completedAt: undefined, callCount: 0, recallCount: 0, notes: '', createdAt: mins(20) },
  { id: 'entry-27', customerId: DEMO_CUSTOMER_ID, branchId: DEMO_BRANCH_ID, queueNumber: 27, billNumber: 'B-1016', customerName: '', phone: '', status: 'waiting', source: 'admin', kitchenStatus: 'pending' as const, joinedAt: mins(15), startedAt: undefined, completedAt: undefined, callCount: 0, recallCount: 0, notes: '', createdAt: mins(15) },
  { id: 'entry-28', customerId: DEMO_CUSTOMER_ID, branchId: DEMO_BRANCH_ID, queueNumber: 28, billNumber: 'B-1017', customerName: '', phone: '', status: 'waiting', source: 'admin', kitchenStatus: 'pending' as const, joinedAt: mins(8), startedAt: undefined, completedAt: undefined, callCount: 0, recallCount: 0, notes: '', createdAt: mins(8) },
]

export const initialActivityLogs: ActivityLog[] = [
  { id: 'log-1', customerId: DEMO_CUSTOMER_ID, branchId: DEMO_BRANCH_ID, entryId: null, performedBy: null, source: 'system', createdAt: mins(65), message: 'Queue #17 completed', type: 'completed', queueNumber: 17, billNumber: 'B-1006' },
  { id: 'log-2', customerId: DEMO_CUSTOMER_ID, branchId: DEMO_BRANCH_ID, entryId: null, performedBy: null, source: 'system', createdAt: mins(5), message: 'Queue #18 called', type: 'called', queueNumber: 18, billNumber: 'B-1007' },
  { id: 'log-3', customerId: DEMO_CUSTOMER_ID, branchId: DEMO_BRANCH_ID, entryId: null, performedBy: null, source: 'system', createdAt: mins(8), message: 'Queue #28 — Bill B-1017', type: 'joined', queueNumber: 28, billNumber: 'B-1017' },
  { id: 'log-4', customerId: DEMO_CUSTOMER_ID, branchId: DEMO_BRANCH_ID, entryId: null, performedBy: null, source: 'system', createdAt: mins(15), message: 'Queue #27 — Bill B-1016', type: 'joined', queueNumber: 27, billNumber: 'B-1016' },
  { id: 'log-5', customerId: DEMO_CUSTOMER_ID, branchId: DEMO_BRANCH_ID, entryId: null, performedBy: null, source: 'system', createdAt: mins(20), message: 'Queue #26 — Bill B-1015', type: 'joined', queueNumber: 26, billNumber: 'B-1015' },
  { id: 'log-6', customerId: DEMO_CUSTOMER_ID, branchId: DEMO_BRANCH_ID, entryId: null, performedBy: null, source: 'system', createdAt: mins(25), message: 'Queue #25 — Bill B-1014', type: 'joined', queueNumber: 25, billNumber: 'B-1014' },
]
